apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-whoami
  labels:
    app: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: {{ .Chart.Name }}-whoami
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent"}}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP

