apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-whoami
spec:
  selector:
    app: whoami
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: http